Fix try block enable mechanism (#1185)
* _HAS_EXCEPTION does not represent to cxx-exception

* Following is the prove:

In file included from D:\a\pltxt2htm\pltxt2htm\cmd\..\include\fast_io/fast_io.h:10:
In file included from D:\a\pltxt2htm\pltxt2htm\cmd\..\include\fast_io\fast_io_hosted.h:19:
In file included from D:\a\pltxt2htm\pltxt2htm\cmd\..\include\fast_io\fast_io_freestanding.h:23:
In file included from D:\a\pltxt2htm\pltxt2htm\cmd\..\include\fast_io\fast_io_freestanding_impl/io_buffer/impl.h:8:
D:\a\pltxt2htm\pltxt2htm\cmd\..\include\fast_io\fast_io_freestanding_impl/io_buffer\destroy.h:41:3: error: cannot use 'try' with exceptions disabled
   41 |                 try
      |                 ^

Because

C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\vcruntime.h:104:33: note: expanded from macro '_HAS_EXCEPTIONS'
  104 |         #define _HAS_EXCEPTIONS 1
      |                                 ^

* exclude clang when detecting msvc

* Add FAST_IO_HAS_EXCEPTIONS macro

* fix case `clang --target=unknown-windows-msvc`

* handle rtti